# Change baseurl before deploy
baseurl = "https://robertodandrea.com"
languageCode = "en-us"
title = "Roberto D'Andrea"

# Google Analytics
googleAnalytics = "G-FDDB8HCY82"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
## This is used to add comment below each post
#disqusShortname = "hugo-theme-stack"

[pagination]
pagerSize = 5

[outputs]
home = ["HTML", "RSS", "SITEMAP", "ROBOTS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true