# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/r-dandrea"

[social.params]
icon = "brand-github"


[[social]]
identifier = "telegram"
name = "Telegram"
url = "https://t.me/Roberto_D_Andrea"

[[social]]
identifier = "email"
name = "Email"
url = "dandrea.ingegnereinformatico@gmail.com"

[social.params]
icon = "brand-telegram"
icon = "brand-email"
